services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: fluxspan-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TIMESCALEDB_TELEMETRY: "off"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  go-worker:
    build:
      context: ./fluxspan-worker
      dockerfile: Dockerfile.dev
    container_name: fluxspan-go-worker
    volumes:
      - ./fluxspan-worker:/app
    environment:
      - APCA_API_KEY_ID=${ALPACA_KEY_ID}
      - APCA_API_SECRET_KEY=${ALPACA_SECRET_KEY}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
